doc: Clone, build, and install xNVMe on the target with -Dwith-spdk=disabled.

steps:
  - name: setup_xnvme
    run: |
      '{{ config.test.repo_path }}/tasks/steps/setup_meson_dep.sh' '{{ config.xnvme.repository.remote }}' '{{ config.xnvme.repository.ref }}' '{{ config.deps.src_root }}/xnvme' '{{ config.deps.build_root }}/xnvme-build' -Dwith-spdk=disabled
