doc: Clone, build, and install the homid daemon and libhomic client on the target.

steps:
  - name: setup_homi
    run: |
      '{{ config.test.repo_path }}/tasks/steps/setup_meson_dep.sh' '{{ config.homi.repository.remote }}' '{{ config.homi.repository.ref }}' '{{ config.deps.src_root }}/homi' '{{ config.deps.build_root }}/homi-build'
