doc: Clone, build, and install xal (eXtent Access Library) on the target.

steps:
  - name: setup_xal
    run: |
      '{{ config.test.repo_path }}/tasks/steps/setup_meson_dep.sh' '{{ config.xal.repository.remote }}' '{{ config.xal.repository.ref }}' '{{ config.deps.src_root }}/xal' '{{ config.deps.build_root }}/xal-build'
